name: Disparando a Action com Push
on:
  push:
    branches:
      - main

jobs:
  push-teste:
    runs-on: ubuntu-latest
    steps:
      - name: Testando o push
        run: |
          echo "O input do workflow_dispatch é: ${{ github.ref_name }}!"