name: Disparando a Action com Push
on:
  # push:
  #   branches:
  #     - main 
  # Linha comentada para não triggar toda hora
  workflow_dispatch:

jobs:
  push-teste:
    runs-on: ubuntu-latest
    steps:
      - name: Testando o push
        run: |
          echo "A branch é: ${{ github.ref_name }}!"