name: Disparando a Action com Cron
on:
  # schedule:
    # - cron: '*/2 * * * *'
    # - cron: '0 12 1 * *'
  workflow_dispatch:

jobs:
  cron-teste:
    runs-on: ubuntu-latest
    env:
      TZ: America/Sao_Paulo
    steps:
      - name: Testando o agendamento
        run: |
          echo "O workflow foi disparado pelo agendamento!"
          echo "Data e hora atual: $(date)"
          echo "Branch atual: ${{ github.ref_name }}"
          echo "Evento: ${{ github.event_name }}"
          echo "Workflow ID: ${{ github.workflow }}"
          echo "Repository: ${{ github.repository }}"