name: Workflow Dispatch
on:
  workflow_dispatch:
    inputs:
      teste:
        description: 'Teste de entrada para o workflow'
        type: string
        default: 'Teste Padrão'
        required: true

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Testando o workflow_dispatch
        run: |
          echo "O input do workflow_dispatch é: ${{ inputs.teste }}!"
